apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
spec:
  storageClassName: {{ .Release.Name }}
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ .Values.mainVolume.dataPath }}
    server: "10.1.8.99"