apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mainVolume.claimName }}
spec:
  storageClassName: {{ .Release.Name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi