apiVersion: v1
kind: Pod
metadata:
  annotations:
    do.hub/username: duongminhhieu16
  labels:
    app: dohub
    heritage: dohub
    do.hub/username: duongminhhieu16
    release: dohub
  name: dohub-duongminhhieu16
  namespace: dohub
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    env:
    - name: PASSWORD
      value: 'daovietanh99'
    image: daovietanh99/deepops
    imagePullPolicy: IfNotPresent
    lifecycle: {}
    name: codeserver
    ports:
    - containerPort: 8443
      name: dohub-port
      protocol: TCP
