kind: Service
apiVersion: v1
metadata:
  name: dohub-daovietanh190499-service
  namespace: dohub
spec:
  selector:
    app: dohub
    heritage: dohub
    do.hub/username: daovietanh190499
    release: dohub
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
    name: user-dohub