kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dohub-handler
  namespace: dohub
rules:
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["patch", "update"]
- apiGroups: [""]
  resources: ["pods/binding"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims", "persistentvolume"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "namespaces"]
  verbs: ["get", "list", "watch"]