kind: Service
apiVersion: v1
metadata:
  name: dohub
  namespace: dohub
spec:
  selector:
    app: dohub
    release: dohub-main-pod
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: dohub
  - protocol: TCP
    port: 80
    targetPort: 80
    name: nginx
  type: LoadBalancer