kind: Service
apiVersion: v1
metadata:
  name: dohub
  namespace: dohub
spec:
  selector:
    app: dohub
    release: dohub-main
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: dohub
  type: LoadBalancer