apiVersion: apps/v1
kind: Deployment
metadata:
  name: dohub
  namespace: dohub
  labels:
    app: dohub
    release: dohub-main
spec:
  selector:
    matchLabels:
      app: dohub
  replicas: 1
  template:
    metadata:
      name: dohub
      namespace: dohub
      labels:
        app: dohub
        release: dohub-main
    spec:
      serviceAccountName: dohub-schedule
      containers:
        - name: dohub
          image: daovietanh99/dohub
          ports:
          - containerPort: 5000
          securityContext:
            capabilities:
              add: ['SYS_ADMIN']
          command: ['python', 'app.py']
          volumeMounts:
            - name: dohub-config
              mountPath: /etc/dohub/config.yaml
              subPath: config.yaml
            - mountPath: /home/dohub
              name: volume-dohub
            - mountPath: /mnt/nas0/
              name: volume-dohub-server
      volumes:
        - name: dohub-config
          configMap:
            name: dohub-config
        - name: volume-dohub
          persistentVolumeClaim:
            claimName: claim-dohub-main
        - name: volume-dohub-server
          persistentVolumeClaim:
            claimName: claim-dohub-server