kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dohub-handler
  namespace: dohub
subjects:
- kind: ServiceAccount
  name: dohub-schedule
  namespace: dohub
roleRef:
  kind: ClusterRole
  name: dohub-handler
  apiGroup: rbac.authorization.k8s.io
