apiVersion: v1
kind: Pod
metadata:
  name: dohub
  namespace: dohub
spec:
  serviceAccountName: dohub-schedule
  containers:
  - name: dohub
    image: daovietanh99/dohub
    securityContext:
      capabilities:
        add: ['SYS_ADMIN']
    command: ['python', 'app.py']
    resources:
      limits:
        cpu: 4
        memory: '8G'