replicaCount: 1

image:
  repository: daovietanh99/dohub
  pullPolicy: Always
  tag: "latest"

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  # annotations: {}
  name: "dohub-service-account"

# podAnnotations: {}
# podLabels: {}

container:
  command: ['/bin/bash', '-c']
  args: [set -a && source .env && set +a && python3 app.py]

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    add: ['SYS_ADMIN']
  allowPrivilegeEscalation: true

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: vkist-hub.com
      paths:
        - path: /
          pathType: Prefix
  tls:
  - secretName: tls-dohub-secret
    hosts:
    - vkist-hub.com

# resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

# tolerations: []

# affinity: {}

volumes:
- name: dohub-configmap
  configMap:
    name: dohub-configmap
- name: dohub-environment
  secret:
    secretName: dohub-secret
- name: volume-dohub-main
  persistentVolumeClaim:
    claimName: claim-dohub-main
- name: volume-dohub-server
  persistentVolumeClaim:
    claimName: claim-dohub-server

volumeMounts:
- name: dohub-configmap
  mountPath: /etc/dohub/config.yaml
  subPath: config.yaml
- mountPath: /mnt/database/
  name: volume-dohub-main
- mountPath: /mnt/nas0/
  name: volume-dohub-server
- mountPath: /home/dohub/.env
  name: dohub-environment
  subPath: .env

configmap:
  path: "configmap/*"
  name: dohub-configmap

secret:
  path: "secrets/*"
  name: dohub-secret

tlssecret:
  name: tls-dohub-secret

pvs:
- name: volume-dohub-server
  storageClassName: volume-dohub-server
  size: 20Gi
  config:
    nfs:
      path: "/data/nas/dohub/"
      server: "10.1.8.99"
- name: volume-dohub-main
  storageClassName: volume-dohub-main
  size: 20Gi
  config:
    nfs:
      path: "/data/nas/dohub/"
      server: "10.1.8.99"

pvcs:
- name: claim-dohub-server
  storageClassName: volume-dohub-server
  size: 20Gi
- name: claim-dohub-main
  storageClassName: volume-dohub-main
  size: 20Gi