# Generated by Django 4.2.13 on 2024-06-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=50)),
                ('docker_image', models.CharField(max_length=50)),
                ('docker_tag', models.CharField(max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('drive', models.CharField(max_length=50)),
                ('gpu', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_access_token', models.CharField(max_length=200)),
                ('github_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('avatar', models.CharField(max_length=200)),
                ('is_accept', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('normal', 'normal')], default='normal', max_length=10)),
                ('state', models.CharField(choices=[('terminated', 'terminated'), ('creating', 'creating'), ('running', 'running'), ('terminating', 'terminating')], default='terminated', max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('inferencing_server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inferencing_server', to='backend.server')),
                ('servers', models.ManyToManyField(null=True, related_name='server_set', to='backend.server')),
            ],
        ),
    ]
