# Generated by Django 5.2 on 2026-06-17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_ssh_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceFileMount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('configmap_key', models.CharField(max_length=253)),
                ('content', models.TextField()),
                ('mount_path', models.CharField(max_length=256)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_mounts', to='backend.workspace')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'unique_together': {('workspace', 'configmap_key'), ('workspace', 'mount_path')},
            },
        ),
    ]
