# Generated by Django 5.2 on 2026-06-17

import backend.models.platform
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_workspacefilemount'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverplantemplate',
            name='file_mounts',
            field=models.JSONField(
                blank=True,
                default=backend.models.platform._default_file_mounts,
                help_text='Default text files, e.g. [{"filename": ".env", "mount_path": "/home/coder/.env", "content": "..."}]',
            ),
        ),
    ]
