apiVersion: v1
kind: Service
metadata:
  name: {{ include "codehub.fullname" . }}
  labels:
    {{- include "codehub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.sshBridge.enabled }}
    - port: {{ .Values.sshBridge.wsPort }}
      targetPort: ssh-ws
      protocol: TCP
      name: ssh-ws
    {{- end }}
    {{- if .Values.portTunnel.enabled }}
    - port: {{ .Values.portTunnel.wsPort }}
      targetPort: port-ws
      protocol: TCP
      name: port-ws
    {{- end }}
    {{- range .Values.service.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "codehub.selectorLabels" . | nindent 4 }}
