{{- if and .Values.sshBridge.enabled .Values.sshBridge.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "codehub.sshBridgeServiceAccountName" . }}
  labels:
    {{- include "codehub.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "codehub.fullname" . }}-ssh-exec
  labels:
    {{- include "codehub.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "codehub.fullname" . }}-ssh-exec
  labels:
    {{- include "codehub.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "codehub.fullname" . }}-ssh-exec
subjects:
  - kind: ServiceAccount
    name: {{ include "codehub.sshBridgeServiceAccountName" . }}
{{- end }}
