kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-dohub-clusterrolesbinding
subjects:
- kind: ServiceAccount
  name: {{ include "dohub.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-dohub-clusterroles
  apiGroup: rbac.authorization.k8s.io