apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dohub
  namespace: {{ .Release.Name }}
  labels:
    app: dohub
    release: {{ .Release.Name }}-dohub-main
spec:
  selector:
    matchLabels:
      app: dohub
  replicas: {{ .Values.dohub.replicas }}
  template:
    metadata:
      name: {{ .Release.Name }}-dohub
      namespace: {{ .Release.Name }}
      labels:
        app: dohub
        release: dohub-main-pod
    spec:
      serviceAccountName: {{ .Release.Name }}-dohub-schedule
      containers:
        - name: {{ .Release.Name }}-dohub-main-container
          image: {{ .Values.global.imageRegistry }}/{{ .Values.dohub.image }}
          imagePullPolicy: Always
          env:
          - name: GITHUB_CLIENT_ID
            value: {{ .Values.dohub.githubClientId }}
          - name: GITHUB_CLIENT_SECRET
            value: {{ .Values.dohub.githubClientSecret }}
          - name: ADMIN_USERS
            value: {{ .Values.dohub.adminUsers }}
          - name: DEFAULT_PORT
            value: {{ .Values.dohub.defaultPort | 8443 }}
          - name: SPAWNER
            value: {{ .Values.dohub.defaultSpawner | 'k8s' }}
          ports:
          - containerPort: 5000
          securityContext:
            capabilities:
              add: ['SYS_ADMIN']
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: {{ .Release.Name }}-dohub-config
              mountPath: /etc/dohub/config.yaml
              subPath: config.yaml
            - mountPath: /mnt/database/
              name: volume-dohub
            - mountPath: /mnt/nas0/
              name: volume-dohub-server
      volumes:
        - name: {{ .Release.Name }}-dohub-config
          configMap:
            name: {{ .Release.Name }}-dohub-config
        - name: volume-dohub
          persistentVolumeClaim:
            claimName: claim-dohub-main
        - name: volume-dohub-server
          persistentVolumeClaim:
            claimName: claim-dohub-server