apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  NAMESPACE: {{ .Release.Namespace }}
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}