kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-dohub-service
  namespace: {{ .Release.Name }}
spec:
  selector:
    app: dohub
    release: dohub-main-pod
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: dohub-main-port
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-dohub-ingress
  namespace: {{ .Release.Name }}
spec:
  tls:
  - hosts:
    - {{ .Values.dohub.domain }}
    secretName: {{ .Release.Name }}-dohub-tls
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}-dohub-service
            port:
              number: 5000