apiVersion: v1
kind: Pod
metadata:
  annotations:
    do.hub/username: daovietanh190499
  labels:
    app: dohub
    heritage: dohub
    do.hub/username: daovietanh190499
    release: dohub
  name: dohub-daovietanh190499
  namespace: dohub
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    env:
    - name: PASSWORD
      value: 'daovietanh99'
    image: daovietanh99/deepops
    imagePullPolicy: IfNotPresent
    lifecycle: {}
    name: codeserver
    ports:
    - containerPort: 8443
      name: code-server-port
      protocol: TCP
    resources:
      limits:
        cpu: "8"
        memory: "17179869184"
        nvidia.com/mig-2g.10gb: "1"
      requests:
        cpu: "8"
        memory: "8589934592"
        nvidia.com/mig-2g.10gb: "1"
    securityContext:
      capabilities:
        add: ['SYS_ADMIN']
      allowPrivilegeEscalation: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/coder
      name: volume-daovietanh190499
    - mountPath: /dev/shm
      name: shm-volume
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  securityContext:
    fsGroup: 100
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - name: volume-daovietanh190499
    persistentVolumeClaim:
      claimName: claim-dohub-daovietanh190499
  - emptyDir:
      medium: Memory
    name: shm-volume