apiVersion: v1
kind: PersistentVolume
metadata:
  name: dohub-daovietanh190499
spec:
  storageClassName: volume-daovietanh190499
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/data/nas/dohub/dohub-daovietanh190499"
    server: "10.1.8.99"