apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jenkins.fullname" . }}-plugins
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
data:
  plugins.txt: |
{{- include "jenkins.pluginsTxt" . | nindent 4 }}
