{{- if not .Values.controller.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins.fullname" . }}-admin
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
type: Opaque
stringData:
  jenkins-admin-user: {{ include "jenkins.adminUser" . | quote }}
  jenkins-admin-password: {{ include "jenkins.adminPassword" . | quote }}
{{- end }}
